### ISSUE TITLE
Initial Issue

### ISSUE THREAD

**Issue by edusanketdk** [edusanketdk/HacktoberFest21#1]
This repository welcomes contributions for HacktoberFest 2021.

**Comment by iamsandipanbera** [comment]
What to contribute?

**Comment by edusanketdk** [comment]
> What to contribute?

you can check the README.md file for more details

**Comment by iamsandipanbera** [comment]
Please take a look #6

**Comment by akankshad1122** [comment]
HI. Are solutions of practice contests acceptable?

**Comment by edusanketdk** [comment]
yes, given they are correct and unique in this repository.
